return PlaceObj('ModDef', {
	'title', "Friendly Expeditions",
	'description', '[h1]This mod allows survivors the ability to tame animals when on an expedition.[/h1]\n[i]This mod is the closest to the vanilla game as posssible[/i]\n\n[h2][b]This mod adds one permanent expedition, called the Idyllic Field![/b][/h2]\n[h2]It also adds new event chains to the "Hunting ground", "Shrieking noises", and "Loud bang" expeditions.[/h2]\n\nAll of the events in this mod will have the player gain a base game tame-able unit.\nAnd can allow players to receive tames from a region they are not building on!\n(For all you pokedex gotcha catch em all players)\n\nThe animal will spawn as close to the expedition balloon that the colonist left on, but you may find that actual location may be farther away if your buildings are too close.\n[i]Please bear that in mind when choosing where to place your Balloons![/i]\n\nIf an expedition has been edited by this mod, you will see it in the expedition title!\n\nI understand it is not super realistic that a Juno will sit in the very small basket of a hot air balloon for hours to come back to a new life.... but hopefully we can just set that aside for immersion/fun purposes.\n\n[url=https://github.com/757Bkob/SAD_FriendlyExpeditions]Friendly Expedition Git![/url]\n[url=https://docs.google.com/spreadsheets/d/1ETvz1lXC7nTnz8EYA3_NCHBmFeGaVeBHGVz_vkvTvOs/edit?usp=sharing]Public Google sheet containing the exported translation table[/url]',
	'image', "Mod/Uqo4QkN/pics or it didn't happen/sample expedition.JPG",
	'last_changes', "1.2 Minor fixes\n\n#1 Bugfix: Idyllic Field expedition will now provide Gujo tames for non-Sobrius maps.\n\n#2 Bugfix: All expedition popups are now marked as Expedition_FollowUps, can trigger more than once (Expect the loud bang expedition), and are not in sets. (TL:DR All expeditions will have a popup occur).\n\nAdded git link and translation table links to description.",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "sad_commonlib",
			'title', "SAD_CommonLib",
			'version_major', 1,
			'version_minor', 12,
		}),
	},
	'id', "Uqo4QkN",
	'author', "Ark Builder",
	'version_major', 1,
	'version_minor', 2,
	'version', 17,
	'lua_revision', 233360,
	'saved_with_revision', 373414,
	'code', {
		"Code/ExpeditionEnhancements.lua",
	},
	'has_data', true,
	'saved', 1786310270,
	'code_hash', -3100342137784193236,
	'steam_id', "3643615905",
	'TagActivities', true,
	'TagAnimals', true,
})